trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'YourAzureSubscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Clone the repository
        git clone https://008443260-Student@dev.azure.com/008443260-Student/Software_Engineering_Spring_2024_Project/_git/Fin-tastic_Division

        # Authenticate with GitHub using Personal Access Token (PAT)
        git config --global user.name "008456949"
        git config --global user.email "008456949@coyote.csusb.edu"
        git config --global credential.helper store
        git config --global credential.github.com.token "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"

        # Push changes to GitHub
        cd Fin-tastic_Division
        git add .
        git commit -m "Automated pipeline update"
        git push origin main
