trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git config --global user.email "008415635@coyote.csusb.edu"
    git config --global user.name "008415635"
    git clone https://github.com/SE-Team-4-2024/Fin-tastic_Division
    cd Fin-tastic_Division
    # Copy files from Azure to GitHub directory
    git add .
    git commit -m "Sync changes from Azure to GitHub"
    git push origin main
  displayName: 'Sync Changes to GitHub'
